### ISSUE TITLE
Invoice is not getting created

### ISSUE THREAD

**Issue by ronnicek** [GiovanniBordiga/lightningtip-PHP#1]
### Background

Tried to install it on my webserver, but invoice is not getting created.

![image](https://user-images.githubusercontent.com/3885042/105923063-1580d100-603c-11eb-80af-7eccb62218bc.png)

### Your environment

* which operating system? Linux
* any other relevant environment details? PHP running in docker, php-curl installed, php 7.3.24
* are you running LightningTip behind a reverse proxy? yes

### Steps to reproduce

Fill up satoshi + memo and click on Get request

Console log, I've enabled console.log("RESPONSE: " + request.responseText):
https://0bin.net/paste/7JIU+fHA#0Cw5PFe0rFHhH5PEO0Q3EXHBbqaX1Ao7BDLaW4q-ybn

### Expected behaviour

Create an invoice

### Actual behaviour

Invoice is not created.

I was trying to find out how to try get invoice from curl, but without any luck :-/

```
 curl --insecure -X POST -d '{"memo":test,"value":1,"expiry":1800}' --header "Grpc-Metadata-macaroon: $(xxd -ps -u -c 1000 ./lnd/data/chain/bitcoin/mainnet/invoice.macaroon)" https://localhost:8080/v1/invoices
{"error":"invalid character 'e' in literal true (expecting 'r')","code":3,"message":"invalid character 'e' in literal true (expecting 'r')","details":[]}
```

**Comment by ronnicek** [comment]
So I was digging around.. and I had typo in curl.. when I put "memo":"test", then it works and create a invoice.. going to dig towards php code then now..

**Comment by ronnicek** [comment]
I tried curl from server where PHP is running, working well.

**Comment by ronnicek** [comment]
So after PHP debugging, I found this:

```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=lnd autogenerated cert; CN=lnd.local
*  start date: Jan 20 21:46:39 2021 GMT
*  expire date: Mar 17 21:46:39 2022 GMT
*  subjectAltName does not match my.epicdomain.com
* SSL: no alternative certificate subject name matches target host name 'my.epicdomain.com'
* Closing connection 0
```

So I added `curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);` and vuala.. PR incoming :)

**Comment by GiovanniBordiga** [comment]
@ronnicek thanks for contributing!

Sorry for the probably dumb question: is the problem related to being behind a reverse proxy?
I asked this because I used the LightningTip server on a [infinityfree.net](https://infinityfree.net/) server and I haven't had any problem there.

**Comment by ronnicek** [comment]
I don't think so that reverse proxy is the issue. Are you have your LND node behind domain name or you are using IP directly?

**Comment by GiovanniBordiga** [comment]
> I don't think so that reverse proxy is the issue. Are you have your LND node behind domain name or you are using IP directly?

I'm using a hostname provided by [noip](https://www.noip.com/).

**Comment by ronnicek** [comment]
Hmm.. and do you have certificate for that noip domain? Can you also send version of PHP and php-curl? I wonder why it's happening to me.. I will try to dig futher on this hopefully during today :)
